version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: backend
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "local", "-d", "backend" ]
      interval: 5s
      timeout: 2s
      retries: 5
    command: postgres -c listen_addresses='*'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

  migrate:
    image: ghcr.io/albardn2/shinkleesh-backend:latest-dev
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "head"]
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://local:local@db:5432/backend"
    networks:
      - proxy

  web:
    image: ghcr.io/albardn2/shinkleesh-backend:latest-dev
    restart: always
    depends_on:
      - db
    # Caddy reverse-proxies to this service inside the network
    expose:
      - "5000"
    env_file:
      - .env
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://local:local@db:5432/backend"
    networks:
      - proxy

  caddy:
    image: caddy:latest
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_HOST: api-dev.shinkleesh.com
      EMAIL: zaid.bardan@gmail.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  proxy:
    driver: bridge
