"""add oauth

Revision ID: 3ed8e34bd18a
Revises: c9d8e7f6a5b4
Create Date: 2026-03-22 17:19:05.756809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed8e34bd18a'
down_revision: Union[str, None] = 'c9d8e7f6a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_user_oauth'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_oauth'), 'user', ['oauth_provider', 'oauth_provider_id'], unique=False)
    # ### end Alembic commands ###
