name: CD – Deploy Dev Stack

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_DROPLET_HOST }}
          username: root
          password: ${{ secrets.DEV_DROPLET_PASSWORD }}
          port: 22
          source: |
            ./backend/docker-compose.dev.yaml
          target: /root/app

      - name: Copy caddy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_DROPLET_HOST }}
          username: root
          password: ${{ secrets.DEV_DROPLET_PASSWORD }}
          port: 22
          source: |
            ./backend/Caddyfile
          target: /root/app

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_DROPLET_HOST }}
          username: root
          password: ${{ secrets.DEV_DROPLET_PASSWORD }}
          port: 22
          script: |
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd /root/app/backend
            docker compose -f docker-compose.dev.yaml down
            docker system prune -af
            cat <<EOF > .env
            APP_HOST=api-dev.shinkleesh.com
            REGISTRY_URL=ghcr.io/albardn2/shinkleesh-backend
            EMAIL=zaid.bardan@gmail.com
            EOF
            docker compose -f docker-compose.dev.yaml pull
            docker compose -f docker-compose.dev.yaml up -d --scale migrate=0 --remove-orphans
